name: 'Hello World'               # action name
description: 'Greet someone'      # description
inputs:
  who-to-greet:                   # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'                 # docker 
  image: 'Dockerfile'             # make image using Dockerfile
  args:                           # set parameter while execute docker run
    - $
